name: Sync Fork on Upstream Update

on:
  repository_dispatch:
    types: [upstream-updated]

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git Identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Add upstream
        run: git remote add upstream https://github.com/K-PaaS-Team22/shelter-web.git

      - name: Fetch remotes
        run: |
          git fetch upstream
          git fetch origin

      - name: Merge upstream/main into fork main
        run: |
          git checkout main
          git merge --no-edit upstream/main || true

      - name: Keep fork's workflows unchanged
        run: |
          # git restore --source=origin/main --staged --worktree .github/workflows/gitlab-mirror.yml
          git restore --source=origin/main --staged --worktree .github/workflows || true

          if ! git diff --quiet || ! git diff --cached --quiet; then
            git commit -am "chore: keep fork workflows unchanged during sync [skip ci]" || true
          fi

      - name: Push to origin
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
